name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Changelog
        id: changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          awk "/## \\[$VERSION\\]/,/^## /" CHANGELOG.md | sed '$d' > RELEASE_NOTES.md

      - name: Update GitHub Release Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
